modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory

[[mods]] #mandatory
	modId="woodenletterblocks" #mandatory
	version="v1.0" #mandatory
	displayName="Wooden Letter Blocks" #mandatory
	description='''Adds wooden letter blocks in different colors and wood types.''' #mandatory
	issueTrackerURL="https://github.com/bl4ckscor3/WoodenLetterBlocks"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/wooden-letter-blocks"
	authors="bl4ckscor3"

[[dependencies.woodenletterblocks]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.woodenletterblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.15)"
    ordering="NONE"
    side="BOTH"